### ISSUE TITLE
Can not find the CGI API Guide anymore

### ISSUE THREAD

**Issue by edydfang** [fbradyirl/hikvision#1]
Hello, I want to develop the function of snapshot for hikvision in python, but I can not find CGI API Guide from the URL resource you give from the README. Is there a backup or something?

**Comment by SP410** [comment]
Any possibility of creating or testing a component in Home Assistant?  https://github.com/home-assistant/home-assistant

I would love to help?

**Comment by fbradyirl** [comment]
Already a component in HA.
