### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by jonathancgroves** [fbradyirl/hikvision#3]
The example script imports `hikvision.py` - the file in the repo is named `api.py` .
I changed the example thus:
`import api

hik_camera = api.CreateDevice(...` and so on.

The script `api.py` imports `hikvision.error` - the error file is named` error.py` , and likewise` hikvision.constants` is named `constants.py` . I changed `api.py` thus:
`from error import...` and so on,
`from constants import...` and so on (once for each of the two references).

Of course, renaming the files is probably the more sensible way!

**Comment by fbradyirl** [comment]
I am not understanding the question here. Be specific.
