### ISSUE TITLE
Control PTZ

### ISSUE THREAD

**Issue by ricciolino** [fbradyirl/hikvision#8]
I have this camera by Hikvision (https://www.hikvision.com/en/products/IP-Products/PTZ-Cameras/Pro-Series/DS-2DE7225IW-AE/?q=ds-2de7225iw-ae&position=2).
By now I'm able to get video stream with rtsp protocol and VideoCapture from opencv.
Is it possible with the API from this repository to control the Pan Tilt Zoom of the camera?

**Comment by ilomon10** [comment]
@fabaff any solution?

**Comment by 17702513221** [comment]
I want know too

**Comment by nhatanh174** [comment]
@ricciolino  hi, did you solve this problem?

**Comment by ricciolino** [comment]
Hi @nhatanh174 , I solved without using this project ... I implemented a small library in C ++ and did the Binding with Python to drive the Camera.
Here is the link to my project!
https://github.com/ricciolino/PyQT_Manager-PTZ_IP_Camera-Hikvision

**Comment by nhatanh174** [comment]
@ricciolino  thanks so much.

**Comment by ricciolino** [comment]
You're welcome!
If you need help, just let me know!

**Comment by surfzoid** [comment]
Hi, in C++, without python, you also have QtVsPlayer whose manage PTZ through Hikvision API
https://github.com/surfzoid/QtVsPlayer
